(define (domain blocks-domain_NORM)
    (:requirements :equality :typing :non-deterministic)
    (:types block - object)
    (:predicates (clear ?b - block)  (emptyhand) (emptyhead) (holding ?b - block)  (on ?b1 - block ?b2 - block)  (on-table ?b - block))
    (:action pick-up
        :parameters (?b1 - block ?b2 - block)
        :precondition (and (not (= ?b1 ?b2)) (emptyhand) (clear ?b1) (on ?b1 ?b2))
        :effect (oneof (and (holding ?b1) (clear ?b2) (not (emptyhand)) (not (clear ?b1)) (not (on ?b1 ?b2))) (and (clear ?b2) (on-table ?b1) (not (on ?b1 ?b2))))
    )
     (:action pick-up-complex01
        :parameters (?b1 - block ?b2 - block)
        :precondition (and (not (= ?b1 ?b2)) (emptyhand) (clear ?b1) (on ?b1 ?b2))
        :effect (oneof (and (clear ?b2) (clear ?b1) (holding ?b1) (not (emptyhand)) (not (clear ?b1)) (not (on ?b1 ?b2))) (and (clear ?b2) (clear ?b1) (on-table ?b1) (not (on ?b1 ?b2))))
    )
     (:action pick-up-empty
        :parameters (?b1 - block ?b2 - block)
        :precondition (and (not (= ?b1 ?b2)) (emptyhand) (clear ?b1) (on ?b1 ?b2))
        :effect (oneof (and ) (and (clear ?b2) (on-table ?b1) (not (on ?b1 ?b2))))
    )
     (:action pick-up-super-complex
        :parameters (?b1 - block ?b2 - block)
        :precondition (and (not (= ?b1 ?b2)) (emptyhand) (clear ?b1) (on ?b1 ?b2))
        :effect (oneof (and (emptyhead) (clear ?b2) (clear ?b1) (emptyhand) (holding ?b1)) (and (emptyhead) (clear ?b2) (clear ?b1) (emptyhand) (holding ?b2)) (and (emptyhead) (clear ?b2) (clear ?b1) (emptyhand) (on ?b1 ?b2)) (and (emptyhead) (holding ?b2) (holding ?b1) (emptyhand)) (and (emptyhead) (holding ?b2) (holding ?b1) (emptyhand)) (and (emptyhead) (holding ?b2) (holding ?b1) (emptyhand) (on ?b1 ?b2)))
    )
)